from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def vioreanu_rokhlin_0(): ...
def vioreanu_rokhlin_1(): ...
def vioreanu_rokhlin_2(): ...
def vioreanu_rokhlin_3(): ...
def vioreanu_rokhlin_4(): ...
def vioreanu_rokhlin_5(): ...
def vioreanu_rokhlin_6(): ...
def vioreanu_rokhlin_7(): ...
def vioreanu_rokhlin_8(): ...
def vioreanu_rokhlin_9(): ...
