from ..helpers import QuadratureScheme as QuadratureScheme, plot_disks_1d as plot_disks_1d
from _typeshed import Incomplete

class C1Scheme(QuadratureScheme):
    domain: str
    def __init__(self, name, degree, weights, points, source: Incomplete | None = ...) -> None: ...
    def integrate(self, f, intervals, domain_shape: Incomplete | None = ..., range_shape: Incomplete | None = ..., dot=...): ...
    def plot(self, interval=..., show_axes: bool = ...) -> None: ...
