# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from decentro_in_kyc_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from decentro_in_kyc_client.model.check_image_quality_response import CheckImageQualityResponse
from decentro_in_kyc_client.model.check_image_quality_response_data import CheckImageQualityResponseData
from decentro_in_kyc_client.model.check_image_quality_response_data_image_quality import CheckImageQualityResponseDataImageQuality
from decentro_in_kyc_client.model.check_image_quality_response_data_image_quality_quality_scores import CheckImageQualityResponseDataImageQualityQualityScores
from decentro_in_kyc_client.model.check_image_quality_response_data_image_quality_quality_scores_compression_quality import CheckImageQualityResponseDataImageQualityQualityScoresCompressionQuality
from decentro_in_kyc_client.model.check_image_quality_response_data_image_quality_quality_scores_text_quality import CheckImageQualityResponseDataImageQualityQualityScoresTextQuality
from decentro_in_kyc_client.model.check_photocopy_response import CheckPhotocopyResponse
from decentro_in_kyc_client.model.check_photocopy_response_data import CheckPhotocopyResponseData
from decentro_in_kyc_client.model.check_video_liveness_response import CheckVideoLivenessResponse
from decentro_in_kyc_client.model.check_video_liveness_response_data import CheckVideoLivenessResponseData
from decentro_in_kyc_client.model.classify_document_response import ClassifyDocumentResponse
from decentro_in_kyc_client.model.classify_document_response_data import ClassifyDocumentResponseData
from decentro_in_kyc_client.model.extract_text_response import ExtractTextResponse
from decentro_in_kyc_client.model.extract_text_response_ocr_result import ExtractTextResponseOcrResult
from decentro_in_kyc_client.model.mask_aadhaar_response import MaskAadhaarResponse
from decentro_in_kyc_client.model.mask_aadhaar_response_data import MaskAadhaarResponseData
from decentro_in_kyc_client.model.match_face_response import MatchFaceResponse
from decentro_in_kyc_client.model.match_face_response_data import MatchFaceResponseData
from decentro_in_kyc_client.model.validate_response import ValidateResponse
from decentro_in_kyc_client.model.validate_response_kyc_result import ValidateResponseKycResult
