"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.case_count_analytics_by_court_geo import CaseCountAnalyticsByCourtGeo
from apollo.model.court_type import CourtType
globals()['CaseCountAnalyticsByCourtGeo'] = CaseCountAnalyticsByCourtGeo
globals()['CourtType'] = CourtType
from apollo.model.case_count_analytics_by_court_type import CaseCountAnalyticsByCourtType


class TestCaseCountAnalyticsByCourtType(unittest.TestCase):
    """CaseCountAnalyticsByCourtType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByCourtType(self):
        """Test CaseCountAnalyticsByCourtType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByCourtType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
