"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.bar_source_data_fees_options_array_inner import BarSourceDataFeesOptionsArrayInner


class TestBarSourceDataFeesOptionsArrayInner(unittest.TestCase):
    """BarSourceDataFeesOptionsArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBarSourceDataFeesOptionsArrayInner(self):
        """Test BarSourceDataFeesOptionsArrayInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BarSourceDataFeesOptionsArrayInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
