"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import unittest

import apollo
from apiv2.case_search_api import CaseSearchApi  # noqa: E501


class TestCaseSearchApi(unittest.TestCase):
    """CaseSearchApi unit test stubs"""

    def setUp(self):
        self.api = CaseSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_cases(self):
        """Test case for search_cases

        Case search.  # noqa: E501
        """
        pass

    def test_search_cases_by_id(self):
        """Test case for search_cases_by_id

        Case search results for a given caseSearchId.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
