"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.bar_source_data_administrative_actions_array_inner import BarSourceDataAdministrativeActionsArrayInner
from apollo.model.bar_source_data_advanced_degree_array_inner import BarSourceDataAdvancedDegreeArrayInner
from apollo.model.bar_source_data_bar_status_array_inner import BarSourceDataBarStatusArrayInner
from apollo.model.bar_source_data_board_certifications_array_inner import BarSourceDataBoardCertificationsArrayInner
from apollo.model.bar_source_data_committees_array_inner import BarSourceDataCommitteesArrayInner
from apollo.model.bar_source_data_court_history_array_inner import BarSourceDataCourtHistoryArrayInner
from apollo.model.bar_source_data_court_of_admissions import BarSourceDataCourtOfAdmissions
from apollo.model.bar_source_data_disciplinary_history_array_inner import BarSourceDataDisciplinaryHistoryArrayInner
from apollo.model.bar_source_data_discipline_summaries_array_inner import BarSourceDataDisciplineSummariesArrayInner
from apollo.model.bar_source_data_employment_history_array_inner import BarSourceDataEmploymentHistoryArrayInner
from apollo.model.bar_source_data_fees_options_array_inner import BarSourceDataFeesOptionsArrayInner
from apollo.model.bar_source_data_involvements_array_inner import BarSourceDataInvolvementsArrayInner
from apollo.model.bar_source_data_law_school_array_inner import BarSourceDataLawSchoolArrayInner
from apollo.model.bar_source_data_name import BarSourceDataName
from apollo.model.bar_source_data_open_action_status_array_inner import BarSourceDataOpenActionStatusArrayInner
from apollo.model.bar_source_data_other_jurisdiction_array_inner import BarSourceDataOtherJurisdictionArrayInner
from apollo.model.bar_source_data_public_hearing_array_inner import BarSourceDataPublicHearingArrayInner
from apollo.model.bar_source_data_reason_for_inactivation import BarSourceDataReasonForInactivation
from apollo.model.bar_source_data_related_cases_array_inner import BarSourceDataRelatedCasesArrayInner
from apollo.model.bar_source_data_source_info import BarSourceDataSourceInfo
from apollo.model.bar_source_data_statewide_grievance_committee_history_array_inner import BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner
from apollo.model.bar_source_data_status_history_array_inner import BarSourceDataStatusHistoryArrayInner
from apollo.model.bar_source_data_ten_year_discipline_array_inner import BarSourceDataTenYearDisciplineArrayInner
globals()['BarSourceDataAdministrativeActionsArrayInner'] = BarSourceDataAdministrativeActionsArrayInner
globals()['BarSourceDataAdvancedDegreeArrayInner'] = BarSourceDataAdvancedDegreeArrayInner
globals()['BarSourceDataBarStatusArrayInner'] = BarSourceDataBarStatusArrayInner
globals()['BarSourceDataBoardCertificationsArrayInner'] = BarSourceDataBoardCertificationsArrayInner
globals()['BarSourceDataCommitteesArrayInner'] = BarSourceDataCommitteesArrayInner
globals()['BarSourceDataCourtHistoryArrayInner'] = BarSourceDataCourtHistoryArrayInner
globals()['BarSourceDataCourtOfAdmissions'] = BarSourceDataCourtOfAdmissions
globals()['BarSourceDataDisciplinaryHistoryArrayInner'] = BarSourceDataDisciplinaryHistoryArrayInner
globals()['BarSourceDataDisciplineSummariesArrayInner'] = BarSourceDataDisciplineSummariesArrayInner
globals()['BarSourceDataEmploymentHistoryArrayInner'] = BarSourceDataEmploymentHistoryArrayInner
globals()['BarSourceDataFeesOptionsArrayInner'] = BarSourceDataFeesOptionsArrayInner
globals()['BarSourceDataInvolvementsArrayInner'] = BarSourceDataInvolvementsArrayInner
globals()['BarSourceDataLawSchoolArrayInner'] = BarSourceDataLawSchoolArrayInner
globals()['BarSourceDataName'] = BarSourceDataName
globals()['BarSourceDataOpenActionStatusArrayInner'] = BarSourceDataOpenActionStatusArrayInner
globals()['BarSourceDataOtherJurisdictionArrayInner'] = BarSourceDataOtherJurisdictionArrayInner
globals()['BarSourceDataPublicHearingArrayInner'] = BarSourceDataPublicHearingArrayInner
globals()['BarSourceDataReasonForInactivation'] = BarSourceDataReasonForInactivation
globals()['BarSourceDataRelatedCasesArrayInner'] = BarSourceDataRelatedCasesArrayInner
globals()['BarSourceDataSourceInfo'] = BarSourceDataSourceInfo
globals()['BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner'] = BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner
globals()['BarSourceDataStatusHistoryArrayInner'] = BarSourceDataStatusHistoryArrayInner
globals()['BarSourceDataTenYearDisciplineArrayInner'] = BarSourceDataTenYearDisciplineArrayInner
from apollo.model.bar_source_data import BarSourceData


class TestBarSourceData(unittest.TestCase):
    """BarSourceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBarSourceData(self):
        """Test BarSourceData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BarSourceData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
