"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.history_value_of_strings import HistoryValueOfStrings


class TestHistoryValueOfStrings(unittest.TestCase):
    """HistoryValueOfStrings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryValueOfStrings(self):
        """Test HistoryValueOfStrings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HistoryValueOfStrings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
