"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.case_count_analytics_by_area_of_law import CaseCountAnalyticsByAreaOfLaw
globals()['CaseCountAnalyticsByAreaOfLaw'] = CaseCountAnalyticsByAreaOfLaw
from apollo.model.case_count_analytics_by_area_of_law_response import CaseCountAnalyticsByAreaOfLawResponse


class TestCaseCountAnalyticsByAreaOfLawResponse(unittest.TestCase):
    """CaseCountAnalyticsByAreaOfLawResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByAreaOfLawResponse(self):
        """Test CaseCountAnalyticsByAreaOfLawResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByAreaOfLawResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
