"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.judges_history import JudgesHistory
globals()['JudgesHistory'] = JudgesHistory
from apollo.model.judges_history_by_date import JudgesHistoryByDate


class TestJudgesHistoryByDate(unittest.TestCase):
    """JudgesHistoryByDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJudgesHistoryByDate(self):
        """Test JudgesHistoryByDate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JudgesHistoryByDate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
