from .._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def taylor_wingate_bos_1(): ...
def taylor_wingate_bos_2(): ...
def taylor_wingate_bos_4(): ...
def taylor_wingate_bos_5(): ...
def taylor_wingate_bos_8(): ...
