# generated by datamodel-codegen:
#   filename:  asset_block_upload_extend_v1.json

from __future__ import annotations

from typing import List

from pydantic import AnyUrl, BaseModel, Extra, Field


class UploadLink(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    uri: AnyUrl = Field(..., description="Pre-signed URL for the uploading each block.")


class FinalizeLink(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    uri: AnyUrl = Field(..., description="Url for completing the upload.")


class ExtendLink(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    uri: AnyUrl = Field(
        ..., description="Url for doing Extend call for getting more pre-signed URLs."
    )


class FieldLinks(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    upload_links: List[UploadLink] = Field(
        ...,
        description="List of Pre-signed URLs for doing the upload for each block.  The upload URLs MUST have the same block size as before.  Clients should immediately start using URLs provided in the extend call , as the service may change the values of existing URLs. However, the Service MUST permit clients to use URLs from any previous version of the URLs received in the initialize/extend call (for the same upload), as it is possible that clients have other inflight-requests already in progress",
        min_items=1,
    )
    finalize_link: FinalizeLink = Field(
        ..., description="URL object for completing the upload."
    )
    extend_link: ExtendLink = Field(
        ...,
        description="URL object for doing Extend call for getting more pre-signed URLs.",
    )


class Model(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    field_links: FieldLinks = Field(..., alias="_links")
    upload_info: str = Field(
        ...,
        description="Encrypted upload info related to this specific upload will be returned in response which needs to be provided as input in extend and finalize calls for extending and finalizing this upload.",
    )
