from ._color_space import ColorSpace as ColorSpace
from ._helpers import register as register
from _typeshed import Incomplete

class HdrLinear(ColorSpace):
    name: str
    invM: Incomplete
    alpha: float
    beta: float
    is_origin_well_defined: bool
    def __init__(self) -> None: ...
    def from_xyz100(self, xyz100): ...
    def to_xyz100(self, hdr_linear): ...
    def from_rgb1(self, hdr1): ...
    def to_rgb1(self, hdr_linear): ...
    def from_rgb255(self, srgb255): ...
    def to_rgb255(self, srgb_linear): ...
