from .._crossref import Crossref as Crossref
from .._tools import dict_to_string as dict_to_string, set_page_range_separator as set_page_range_separator, write as write
from .helpers import add_formatting_parser_arguments as add_formatting_parser_arguments

def run(args) -> None: ...
def add_args(parser) -> None: ...
