from .._tools import bibtex_parser as bibtex_parser, dict_to_string as dict_to_string, set_page_range_separator as set_page_range_separator, write as write
from ..journal_abbrev import journal_abbrev as journal_abbrev
from .helpers import add_file_parser_arguments as add_file_parser_arguments, add_formatting_parser_arguments as add_formatting_parser_arguments

def run(args) -> None: ...
def add_args(parser) -> None: ...
