from _typeshed import Incomplete

def parse_into_latex_tree(string: str): ...
def unicode_to_latex_tree(lst: list): ...
def merge_strings(lst: list): ...
def tree_to_string(lst: list): ...

class NodeTransformer:
    def visit_str(self, node): ...
    def visit_BraceGroup(self, node): ...
    def visit_InlineMath(self, node): ...
    def visit(self, lst): ...

class CategoryParser:
    string: Incomplete
    makeatletter: bool
    def __init__(self, string: str) -> None: ...
    def parse_categories(self, is_dollar_math: bool = ...): ...

class BraceGroup:
    children: Incomplete
    def __init__(self, children: list) -> None: ...

class InlineMath:
    children: Incomplete
    def __init__(self, children) -> None: ...
