from ..helpers import article as article
from ._helpers import S2Scheme as S2Scheme, register as register
from _typeshed import Incomplete

frac: Incomplete
pi: Incomplete
cos: Incomplete
sin: Incomplete
sqrt: Incomplete
pm_: Incomplete
roots: Incomplete
linear_solve: Incomplete

def albrecht_1(): ...
def albrecht_2(): ...
def albrecht_3(): ...
def albrecht_4(): ...
def albrecht_5(): ...
def albrecht_6(): ...
def albrecht_7(): ...
def albrecht_8(): ...
