from ..helpers import article as article
from ._helpers import S2Scheme as S2Scheme, register as register
from ._peirce_1956 import peirce_1956_1 as peirce_1956_1, peirce_1956_3 as peirce_1956_3
from ._radon import radon as radon
from _typeshed import Incomplete

frac: Incomplete
pi: Incomplete
sqrt: Incomplete
pm_: Incomplete
cos: Incomplete
sin: Incomplete

def hammer_stroud_12_2(): ...
def hammer_stroud_13_2(): ...
def hammer_stroud_17(): ...
def hammer_stroud_18(): ...
def hammer_stroud_19(): ...
def hammer_stroud_20(): ...
def hammer_stroud_21(): ...
