from ..helpers import article as article, untangle as untangle
from ._helpers import S2Scheme as S2Scheme, register as register

def wissmann_becker_6_1(): ...
def wissmann_becker_6_2(): ...
def wissmann_becker_8_1(): ...
