from numpy.typing import ArrayLike as ArrayLike

def bianco_schettini(whitepoint_source: ArrayLike, whitepoint_target: ArrayLike): ...
def bianco_schettini_pos(whitepoint_source: ArrayLike, whitepoint_target: ArrayLike): ...
