from typing import Callable

class NewtonConvergenceError(Exception): ...

def newton(f: Callable, jacobian_solver: Callable, norm2: Callable, u0, tol: float = ..., max_iter: int = ..., verbose: bool = ...): ...
