# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from commonfate import schemas  # noqa: F401


class ApprovalMethod(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Describes whether a request has been approved automatically or from a review 
    """


    class MetaOapg:
        enum_value_to_name = {
            "AUTOMATIC": "AUTOMATIC",
            "REVIEWED": "REVIEWED",
        }
    
    @schemas.classproperty
    def AUTOMATIC(cls):
        return cls("AUTOMATIC")
    
    @schemas.classproperty
    def REVIEWED(cls):
        return cls("REVIEWED")
