# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import commonfate
from commonfate.model.request_event import RequestEvent
from commonfate import configuration


class TestRequestEvent(unittest.TestCase):
    """RequestEvent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
