from ..helpers import article as article, expand_symmetries as expand_symmetries, prod as prod
from ._helpers import CnScheme as CnScheme

def cools_haegemans_1(n, delta2: int = ..., symbolic: bool = ...): ...
def cools_haegemans_2(n, delta2: int = ..., symbolic: bool = ...): ...
