from ..helpers import article as article, expand_symmetries as expand_symmetries, fsd as fsd, untangle as untangle, z as z
from ._helpers import CnScheme as CnScheme

def hammer_stroud_1n(n): ...
def hammer_stroud_2n(n): ...
