from .._exception import QuadpyError as QuadpyError
from ..helpers import QuadratureScheme as QuadratureScheme, n_outer as n_outer
from _typeshed import Incomplete
from typing import Callable

class CnScheme(QuadratureScheme):
    domain: Incomplete
    dim: Incomplete
    def __init__(self, name: str, dim: int, weights, points, degree: int, source, tol: float = ..., comments: Incomplete | None = ...) -> None: ...
    def integrate(self, f: Callable, ncube, dot=...): ...
    def points_inside(self): ...
    def points_inside_or_boundary(self): ...

def transform(xi, cube): ...
def get_detJ(xi, cube): ...
def integrate_monomial_over_ncube(ncube_limits, exp): ...
def ncube_points(*xyz): ...
