from ..helpers import article as article, comb as comb, fsd as fsd, prod as prod, untangle as untangle, z as z
from ._helpers import CnScheme as CnScheme

def integrator(n, k, symbolic): ...
def mcnamee_stenger_3(n, symbolic: bool = ...): ...
def mcnamee_stenger_5(n, symbolic: bool = ...): ...
def mcnamee_stenger_7a(n, symbolic: bool = ...): ...
def mcnamee_stenger_7b(n, symbolic: bool = ...): ...
def mcnamee_stenger_9a(n, symbolic: bool = ...): ...
def mcnamee_stenger_9b(n, symbolic: bool = ...): ...
