from ..helpers import article as article, expand_symmetries as expand_symmetries, pm as pm, untangle as untangle, z as z
from ._helpers import CnScheme as CnScheme

def stroud_1966_a(n): ...
def stroud_1966_b(n): ...
def stroud_1966_c(n): ...
def stroud_1966_d(n): ...
