from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
c2: Incomplete
this_dir: Incomplete

def dcutri(): ...
def berntsen_espelid_1(): ...
def berntsen_espelid_2(): ...
def berntsen_espelid_3(): ...
def berntsen_espelid_4(): ...
