from ..helpers import QuadratureScheme as QuadratureScheme, backend_to_function as backend_to_function

class W3Scheme(QuadratureScheme):
    domain: str
    def __init__(self, name, weights, points, degree, source, tol: float = ...) -> None: ...
    def integrate(self, f, wedge, dot=...): ...
    def show(self, wedge=..., backend: str = ...): ...
