
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-05T18:16:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "adffef521b92997b10f4bd51275c582bfc380a82",
 "version": "1.48.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
