from ..helpers import QuadratureScheme as QuadratureScheme, plot_disks as plot_disks
from _typeshed import Incomplete

schemes: Incomplete

def register(in_schemes) -> None: ...

class U2Scheme(QuadratureScheme):
    domain: str
    def __init__(self, name, source, degree, weights, points, tol) -> None: ...
    def show(self, *args, **kwargs) -> None: ...
    def plot(self, show_axes: bool = ...) -> None: ...
    def integrate(self, f, center, radius, dot=...): ...

def get_good_scheme(n): ...
