# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/live/models.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ho_protocols/live/models.proto',
  package='ho.live.models',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eho_protocols/live/models.proto\x12\x0eho.live.models\"\xce\x01\n\rModelLiveItem\x12\x33\n\x0charvest_time\x18\x01 \x01(\x0b\x32\x1b.ho.live.models.HarvestTimeH\x00\x12\x39\n\x0f\x63olony_collapse\x18\x02 \x01(\x0b\x32\x1e.ho.live.models.ColonyCollapseH\x00\x12\x43\n\x14harvesting_procedure\x18\x03 \x01(\x0b\x32#.ho.live.models.HarvestingProcedureH\x00\x42\x08\n\x06models\"\x8d\x01\n\x0bHarvestTime\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".ho.live.models.HarvestTime.Status\x12\x0e\n\x06weight\x18\x02 \x01(\x02\":\n\x06Status\x12\x0b\n\x07Unknown\x10\x00\x12\x0f\n\x0bNotReadyYet\x10\x01\x12\x12\n\x0eReadyToHarvest\x10\x02\".\n\x0e\x43olonyCollapse\x12\x1c\n\x14\x63ollapse_probability\x18\x01 \x01(\x02\"\xad\x01\n\x13HarvestingProcedure\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.ho.live.models.HarvestingProcedure.Status\x12\x18\n\x10harvested_amount\x18\x02 \x01(\x02\"@\n\x06Status\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Success\x10\x01\x12\x0f\n\x0bInterrupted\x10\x02\x12\x0b\n\x07\x46\x61ilure\x10\x03\x42\x02H\x03\x62\x06proto3'
)



_HARVESTTIME_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ho.live.models.HarvestTime.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NotReadyYet', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ReadyToHarvest', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=343,
  serialized_end=401,
)
_sym_db.RegisterEnumDescriptor(_HARVESTTIME_STATUS)

_HARVESTINGPROCEDURE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ho.live.models.HarvestingProcedure.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Success', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Interrupted', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failure', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=561,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_HARVESTINGPROCEDURE_STATUS)


_MODELLIVEITEM = _descriptor.Descriptor(
  name='ModelLiveItem',
  full_name='ho.live.models.ModelLiveItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='harvest_time', full_name='ho.live.models.ModelLiveItem.harvest_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colony_collapse', full_name='ho.live.models.ModelLiveItem.colony_collapse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='harvesting_procedure', full_name='ho.live.models.ModelLiveItem.harvesting_procedure', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='models', full_name='ho.live.models.ModelLiveItem.models',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=51,
  serialized_end=257,
)


_HARVESTTIME = _descriptor.Descriptor(
  name='HarvestTime',
  full_name='ho.live.models.HarvestTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ho.live.models.HarvestTime.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='ho.live.models.HarvestTime.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HARVESTTIME_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=401,
)


_COLONYCOLLAPSE = _descriptor.Descriptor(
  name='ColonyCollapse',
  full_name='ho.live.models.ColonyCollapse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='collapse_probability', full_name='ho.live.models.ColonyCollapse.collapse_probability', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=449,
)


_HARVESTINGPROCEDURE = _descriptor.Descriptor(
  name='HarvestingProcedure',
  full_name='ho.live.models.HarvestingProcedure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ho.live.models.HarvestingProcedure.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='harvested_amount', full_name='ho.live.models.HarvestingProcedure.harvested_amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HARVESTINGPROCEDURE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=625,
)

_MODELLIVEITEM.fields_by_name['harvest_time'].message_type = _HARVESTTIME
_MODELLIVEITEM.fields_by_name['colony_collapse'].message_type = _COLONYCOLLAPSE
_MODELLIVEITEM.fields_by_name['harvesting_procedure'].message_type = _HARVESTINGPROCEDURE
_MODELLIVEITEM.oneofs_by_name['models'].fields.append(
  _MODELLIVEITEM.fields_by_name['harvest_time'])
_MODELLIVEITEM.fields_by_name['harvest_time'].containing_oneof = _MODELLIVEITEM.oneofs_by_name['models']
_MODELLIVEITEM.oneofs_by_name['models'].fields.append(
  _MODELLIVEITEM.fields_by_name['colony_collapse'])
_MODELLIVEITEM.fields_by_name['colony_collapse'].containing_oneof = _MODELLIVEITEM.oneofs_by_name['models']
_MODELLIVEITEM.oneofs_by_name['models'].fields.append(
  _MODELLIVEITEM.fields_by_name['harvesting_procedure'])
_MODELLIVEITEM.fields_by_name['harvesting_procedure'].containing_oneof = _MODELLIVEITEM.oneofs_by_name['models']
_HARVESTTIME.fields_by_name['status'].enum_type = _HARVESTTIME_STATUS
_HARVESTTIME_STATUS.containing_type = _HARVESTTIME
_HARVESTINGPROCEDURE.fields_by_name['status'].enum_type = _HARVESTINGPROCEDURE_STATUS
_HARVESTINGPROCEDURE_STATUS.containing_type = _HARVESTINGPROCEDURE
DESCRIPTOR.message_types_by_name['ModelLiveItem'] = _MODELLIVEITEM
DESCRIPTOR.message_types_by_name['HarvestTime'] = _HARVESTTIME
DESCRIPTOR.message_types_by_name['ColonyCollapse'] = _COLONYCOLLAPSE
DESCRIPTOR.message_types_by_name['HarvestingProcedure'] = _HARVESTINGPROCEDURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelLiveItem = _reflection.GeneratedProtocolMessageType('ModelLiveItem', (_message.Message,), {
  'DESCRIPTOR' : _MODELLIVEITEM,
  '__module__' : 'ho_protocols.live.models_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.models.ModelLiveItem)
  })
_sym_db.RegisterMessage(ModelLiveItem)

HarvestTime = _reflection.GeneratedProtocolMessageType('HarvestTime', (_message.Message,), {
  'DESCRIPTOR' : _HARVESTTIME,
  '__module__' : 'ho_protocols.live.models_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.models.HarvestTime)
  })
_sym_db.RegisterMessage(HarvestTime)

ColonyCollapse = _reflection.GeneratedProtocolMessageType('ColonyCollapse', (_message.Message,), {
  'DESCRIPTOR' : _COLONYCOLLAPSE,
  '__module__' : 'ho_protocols.live.models_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.models.ColonyCollapse)
  })
_sym_db.RegisterMessage(ColonyCollapse)

HarvestingProcedure = _reflection.GeneratedProtocolMessageType('HarvestingProcedure', (_message.Message,), {
  'DESCRIPTOR' : _HARVESTINGPROCEDURE,
  '__module__' : 'ho_protocols.live.models_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.models.HarvestingProcedure)
  })
_sym_db.RegisterMessage(HarvestingProcedure)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
