from .._helpers import T3Scheme as T3Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def keast_0(): ...
def keast_1(): ...
def keast_2(): ...
def keast_3(): ...
def keast_4(): ...
def keast_5(): ...
def keast_6(): ...
def keast_7(): ...
def keast_8(): ...
def keast_9(): ...
