from ..helpers import QuadratureScheme as QuadratureScheme, expand_symmetries as expand_symmetries, plot_disks as plot_disks
from _typeshed import Incomplete

schemes: Incomplete

def register(in_schemes) -> None: ...

class E2rScheme(QuadratureScheme):
    domain: str
    symmetry_data: Incomplete
    def __init__(self, name, symmetry_data, degree, source, tol: float = ..., weight_factor: Incomplete | None = ...) -> None: ...
    def plot(self, show_axes: bool = ...) -> None: ...
    def integrate(self, f, dot=...): ...

def get_good_scheme(degree): ...
