from .._helpers import register as register
from _typeshed import Incomplete

this_dir: Incomplete

def kim_song_1(): ...
def kim_song_2(): ...
def kim_song_3(): ...
def kim_song_4(): ...
def kim_song_5(): ...
def kim_song_6(): ...
def kim_song_7(): ...
def kim_song_8(): ...
def kim_song_9(): ...
def kim_song_10(): ...
def kim_song_11(): ...
def kim_song_12(): ...
def kim_song_13(): ...
def kim_song_14(): ...
def kim_song_15(): ...
