# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/alert/system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ho_protocols/alert/system.proto',
  package='ho.alert.system',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fho_protocols/alert/system.proto\x12\x0fho.alert.system\"\x9e\x02\n\x0bSystemAlert\x12G\n\x16\x62roodnest_overeheating\x18\x01 \x01(\x0b\x32%.ho.alert.system.BroodnestOverheatingH\x00\x12\x36\n\rpower_failure\x18\x02 \x01(\x0b\x32\x1d.ho.alert.system.PowerFailureH\x00\x12@\n\x12harvesting_failure\x18\x03 \x01(\x0b\x32\".ho.alert.system.HarvestingFailureH\x00\x12\x44\n\x14harvesting_interrupt\x18\x04 \x01(\x0b\x32$.ho.alert.system.HarvestingInterruptH\x00\x42\x06\n\x04type\"<\n\x14\x42roodnestOverheating\x12\x11\n\tmean_temp\x18\x01 \x01(\x02\x12\x11\n\tsensor_id\x18\x02 \x01(\t\"\x0e\n\x0cPowerFailure\"#\n\x11HarvestingFailure\x12\x0e\n\x06reason\x18\x01 \x01(\t\"%\n\x13HarvestingInterrupt\x12\x0e\n\x06reason\x18\x01 \x01(\tB\x02H\x03\x62\x06proto3'
)




_SYSTEMALERT = _descriptor.Descriptor(
  name='SystemAlert',
  full_name='ho.alert.system.SystemAlert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broodnest_overeheating', full_name='ho.alert.system.SystemAlert.broodnest_overeheating', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_failure', full_name='ho.alert.system.SystemAlert.power_failure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='harvesting_failure', full_name='ho.alert.system.SystemAlert.harvesting_failure', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='harvesting_interrupt', full_name='ho.alert.system.SystemAlert.harvesting_interrupt', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ho.alert.system.SystemAlert.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=53,
  serialized_end=339,
)


_BROODNESTOVERHEATING = _descriptor.Descriptor(
  name='BroodnestOverheating',
  full_name='ho.alert.system.BroodnestOverheating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean_temp', full_name='ho.alert.system.BroodnestOverheating.mean_temp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='ho.alert.system.BroodnestOverheating.sensor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=401,
)


_POWERFAILURE = _descriptor.Descriptor(
  name='PowerFailure',
  full_name='ho.alert.system.PowerFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=417,
)


_HARVESTINGFAILURE = _descriptor.Descriptor(
  name='HarvestingFailure',
  full_name='ho.alert.system.HarvestingFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='ho.alert.system.HarvestingFailure.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=454,
)


_HARVESTINGINTERRUPT = _descriptor.Descriptor(
  name='HarvestingInterrupt',
  full_name='ho.alert.system.HarvestingInterrupt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='ho.alert.system.HarvestingInterrupt.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=493,
)

_SYSTEMALERT.fields_by_name['broodnest_overeheating'].message_type = _BROODNESTOVERHEATING
_SYSTEMALERT.fields_by_name['power_failure'].message_type = _POWERFAILURE
_SYSTEMALERT.fields_by_name['harvesting_failure'].message_type = _HARVESTINGFAILURE
_SYSTEMALERT.fields_by_name['harvesting_interrupt'].message_type = _HARVESTINGINTERRUPT
_SYSTEMALERT.oneofs_by_name['type'].fields.append(
  _SYSTEMALERT.fields_by_name['broodnest_overeheating'])
_SYSTEMALERT.fields_by_name['broodnest_overeheating'].containing_oneof = _SYSTEMALERT.oneofs_by_name['type']
_SYSTEMALERT.oneofs_by_name['type'].fields.append(
  _SYSTEMALERT.fields_by_name['power_failure'])
_SYSTEMALERT.fields_by_name['power_failure'].containing_oneof = _SYSTEMALERT.oneofs_by_name['type']
_SYSTEMALERT.oneofs_by_name['type'].fields.append(
  _SYSTEMALERT.fields_by_name['harvesting_failure'])
_SYSTEMALERT.fields_by_name['harvesting_failure'].containing_oneof = _SYSTEMALERT.oneofs_by_name['type']
_SYSTEMALERT.oneofs_by_name['type'].fields.append(
  _SYSTEMALERT.fields_by_name['harvesting_interrupt'])
_SYSTEMALERT.fields_by_name['harvesting_interrupt'].containing_oneof = _SYSTEMALERT.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['SystemAlert'] = _SYSTEMALERT
DESCRIPTOR.message_types_by_name['BroodnestOverheating'] = _BROODNESTOVERHEATING
DESCRIPTOR.message_types_by_name['PowerFailure'] = _POWERFAILURE
DESCRIPTOR.message_types_by_name['HarvestingFailure'] = _HARVESTINGFAILURE
DESCRIPTOR.message_types_by_name['HarvestingInterrupt'] = _HARVESTINGINTERRUPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemAlert = _reflection.GeneratedProtocolMessageType('SystemAlert', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMALERT,
  '__module__' : 'ho_protocols.alert.system_pb2'
  # @@protoc_insertion_point(class_scope:ho.alert.system.SystemAlert)
  })
_sym_db.RegisterMessage(SystemAlert)

BroodnestOverheating = _reflection.GeneratedProtocolMessageType('BroodnestOverheating', (_message.Message,), {
  'DESCRIPTOR' : _BROODNESTOVERHEATING,
  '__module__' : 'ho_protocols.alert.system_pb2'
  # @@protoc_insertion_point(class_scope:ho.alert.system.BroodnestOverheating)
  })
_sym_db.RegisterMessage(BroodnestOverheating)

PowerFailure = _reflection.GeneratedProtocolMessageType('PowerFailure', (_message.Message,), {
  'DESCRIPTOR' : _POWERFAILURE,
  '__module__' : 'ho_protocols.alert.system_pb2'
  # @@protoc_insertion_point(class_scope:ho.alert.system.PowerFailure)
  })
_sym_db.RegisterMessage(PowerFailure)

HarvestingFailure = _reflection.GeneratedProtocolMessageType('HarvestingFailure', (_message.Message,), {
  'DESCRIPTOR' : _HARVESTINGFAILURE,
  '__module__' : 'ho_protocols.alert.system_pb2'
  # @@protoc_insertion_point(class_scope:ho.alert.system.HarvestingFailure)
  })
_sym_db.RegisterMessage(HarvestingFailure)

HarvestingInterrupt = _reflection.GeneratedProtocolMessageType('HarvestingInterrupt', (_message.Message,), {
  'DESCRIPTOR' : _HARVESTINGINTERRUPT,
  '__module__' : 'ho_protocols.alert.system_pb2'
  # @@protoc_insertion_point(class_scope:ho.alert.system.HarvestingInterrupt)
  })
_sym_db.RegisterMessage(HarvestingInterrupt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
