from .._helpers import register as register
from _typeshed import Incomplete

this_dir: Incomplete

def luo_meng_1(): ...
def luo_meng_2(): ...
def luo_meng_3(): ...
def luo_meng_4(): ...
def luo_meng_5(): ...
def luo_meng_6(): ...
