from .._helpers import C2Scheme as C2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def dunavant_00(): ...
def dunavant_01(): ...
def dunavant_02(): ...
def dunavant_04(): ...
def dunavant_05(): ...
def dunavant_06(): ...
def dunavant_07(): ...
def dunavant_08(): ...
def dunavant_09(): ...
def dunavant_10(): ...
