# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.update_user_role_request import UpdateUserRoleRequest
from openapi_client import configuration


class TestUpdateUserRoleRequest(unittest.TestCase):
    """UpdateUserRoleRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
