from ..helpers import article as article, fsd as fsd, pm as pm, untangle as untangle, z as z
from ._helpers import Enr2Scheme as Enr2Scheme

def cools_haegemans_1(n, delta2: int = ..., symbolic: bool = ...): ...
def cools_haegemans_2(n, delta2: int = ..., symbolic: bool = ...): ...
def cools_haegemans_3(n, delta2=..., symbolic: bool = ...): ...
