from .._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def laursen_gellert_02a(): ...
def laursen_gellert_02b(): ...
def laursen_gellert_06(): ...
def laursen_gellert_07(): ...
def laursen_gellert_08(): ...
def laursen_gellert_09(): ...
def laursen_gellert_10(): ...
def laursen_gellert_11(): ...
def laursen_gellert_12(): ...
def laursen_gellert_13(): ...
def laursen_gellert_14(): ...
def laursen_gellert_15a(): ...
def laursen_gellert_15b(): ...
