# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/live/sensors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ho_protocols/live/sensors.proto',
  package='ho.live.sensors',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fho_protocols/live/sensors.proto\x12\x0fho.live.sensors\"\xe8\x01\n\x0eSensorLiveItem\x12/\n\tbroodnest\x18\x01 \x01(\x0b\x32\x1a.ho.live.sensors.BroodnestH\x00\x12\x34\n\x0ctraffic_flow\x18\x02 \x01(\x0b\x32\x1c.ho.live.sensors.TrafficFlowH\x00\x12.\n\x0bhive_scales\x18\x03 \x01(\x0b\x32\x17.ho.live.sensors.ScalesH\x00\x12\x34\n\x0cpower_supply\x18\x04 \x01(\x0b\x32\x1c.ho.live.sensors.PowerSupplyH\x00\x42\t\n\x07sensors\"2\n\tBroodnest\x12\x0c\n\x04temp\x18\x01 \x03(\x02\x12\n\n\x02rh\x18\x02 \x03(\x02\x12\x0b\n\x03\x63o2\x18\x03 \x01(\x02\"0\n\x0bTrafficFlow\x12\x0f\n\x07\x62\x65\x65s_in\x18\x01 \x01(\x02\x12\x10\n\x08\x62\x65\x65s_out\x18\x02 \x01(\x02\"\x18\n\x06Scales\x12\x0e\n\x06weight\x18\x01 \x01(\x02\"\xb2\x01\n\x0bPowerSupply\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x14\n\x0c\x63urrent_draw\x18\x02 \x01(\x02\x12\x14\n\x0c\x63urrent_rate\x18\x03 \x01(\x02\x12\x31\n\x05level\x18\x04 \x01(\x0e\x32\".ho.live.sensors.PowerSupply.Level\"3\n\x05Level\x12\x0b\n\x07Unknown\x10\x00\x12\x07\n\x03Low\x10\x01\x12\n\n\x06Medium\x10\x02\x12\x08\n\x04High\x10\x03\x42\x02H\x03\x62\x06proto3'
)



_POWERSUPPLY_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='ho.live.sensors.PowerSupply.Level',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Low', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Medium', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='High', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=543,
  serialized_end=594,
)
_sym_db.RegisterEnumDescriptor(_POWERSUPPLY_LEVEL)


_SENSORLIVEITEM = _descriptor.Descriptor(
  name='SensorLiveItem',
  full_name='ho.live.sensors.SensorLiveItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broodnest', full_name='ho.live.sensors.SensorLiveItem.broodnest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_flow', full_name='ho.live.sensors.SensorLiveItem.traffic_flow', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hive_scales', full_name='ho.live.sensors.SensorLiveItem.hive_scales', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_supply', full_name='ho.live.sensors.SensorLiveItem.power_supply', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sensors', full_name='ho.live.sensors.SensorLiveItem.sensors',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=53,
  serialized_end=285,
)


_BROODNEST = _descriptor.Descriptor(
  name='Broodnest',
  full_name='ho.live.sensors.Broodnest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='ho.live.sensors.Broodnest.temp', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rh', full_name='ho.live.sensors.Broodnest.rh', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='co2', full_name='ho.live.sensors.Broodnest.co2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=337,
)


_TRAFFICFLOW = _descriptor.Descriptor(
  name='TrafficFlow',
  full_name='ho.live.sensors.TrafficFlow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bees_in', full_name='ho.live.sensors.TrafficFlow.bees_in', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bees_out', full_name='ho.live.sensors.TrafficFlow.bees_out', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=387,
)


_SCALES = _descriptor.Descriptor(
  name='Scales',
  full_name='ho.live.sensors.Scales',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='ho.live.sensors.Scales.weight', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=413,
)


_POWERSUPPLY = _descriptor.Descriptor(
  name='PowerSupply',
  full_name='ho.live.sensors.PowerSupply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='ho.live.sensors.PowerSupply.voltage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_draw', full_name='ho.live.sensors.PowerSupply.current_draw', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_rate', full_name='ho.live.sensors.PowerSupply.current_rate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='ho.live.sensors.PowerSupply.level', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POWERSUPPLY_LEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=594,
)

_SENSORLIVEITEM.fields_by_name['broodnest'].message_type = _BROODNEST
_SENSORLIVEITEM.fields_by_name['traffic_flow'].message_type = _TRAFFICFLOW
_SENSORLIVEITEM.fields_by_name['hive_scales'].message_type = _SCALES
_SENSORLIVEITEM.fields_by_name['power_supply'].message_type = _POWERSUPPLY
_SENSORLIVEITEM.oneofs_by_name['sensors'].fields.append(
  _SENSORLIVEITEM.fields_by_name['broodnest'])
_SENSORLIVEITEM.fields_by_name['broodnest'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['sensors']
_SENSORLIVEITEM.oneofs_by_name['sensors'].fields.append(
  _SENSORLIVEITEM.fields_by_name['traffic_flow'])
_SENSORLIVEITEM.fields_by_name['traffic_flow'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['sensors']
_SENSORLIVEITEM.oneofs_by_name['sensors'].fields.append(
  _SENSORLIVEITEM.fields_by_name['hive_scales'])
_SENSORLIVEITEM.fields_by_name['hive_scales'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['sensors']
_SENSORLIVEITEM.oneofs_by_name['sensors'].fields.append(
  _SENSORLIVEITEM.fields_by_name['power_supply'])
_SENSORLIVEITEM.fields_by_name['power_supply'].containing_oneof = _SENSORLIVEITEM.oneofs_by_name['sensors']
_POWERSUPPLY.fields_by_name['level'].enum_type = _POWERSUPPLY_LEVEL
_POWERSUPPLY_LEVEL.containing_type = _POWERSUPPLY
DESCRIPTOR.message_types_by_name['SensorLiveItem'] = _SENSORLIVEITEM
DESCRIPTOR.message_types_by_name['Broodnest'] = _BROODNEST
DESCRIPTOR.message_types_by_name['TrafficFlow'] = _TRAFFICFLOW
DESCRIPTOR.message_types_by_name['Scales'] = _SCALES
DESCRIPTOR.message_types_by_name['PowerSupply'] = _POWERSUPPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorLiveItem = _reflection.GeneratedProtocolMessageType('SensorLiveItem', (_message.Message,), {
  'DESCRIPTOR' : _SENSORLIVEITEM,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.SensorLiveItem)
  })
_sym_db.RegisterMessage(SensorLiveItem)

Broodnest = _reflection.GeneratedProtocolMessageType('Broodnest', (_message.Message,), {
  'DESCRIPTOR' : _BROODNEST,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.Broodnest)
  })
_sym_db.RegisterMessage(Broodnest)

TrafficFlow = _reflection.GeneratedProtocolMessageType('TrafficFlow', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICFLOW,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.TrafficFlow)
  })
_sym_db.RegisterMessage(TrafficFlow)

Scales = _reflection.GeneratedProtocolMessageType('Scales', (_message.Message,), {
  'DESCRIPTOR' : _SCALES,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.Scales)
  })
_sym_db.RegisterMessage(Scales)

PowerSupply = _reflection.GeneratedProtocolMessageType('PowerSupply', (_message.Message,), {
  'DESCRIPTOR' : _POWERSUPPLY,
  '__module__' : 'ho_protocols.live.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ho.live.sensors.PowerSupply)
  })
_sym_db.RegisterMessage(PowerSupply)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
