
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-02T22:50:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2766a09d00530b055f10593b3cf5041adc10315e",
 "version": "0.2.63.post0.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
