from ._helpers import C2Scheme as C2Scheme, register as register
from ._rabinowitz_richter import rabinowitz_richter_1 as rabinowitz_richter_1
from ._tyler import tyler_2 as tyler_2

def franke_1(lmbda: int = ...): ...
def franke_2a(): ...
def franke_2b(): ...
def franke_3a(): ...
def franke_3b(): ...
def franke_3c(): ...
def franke_5(): ...
def franke_6(): ...
def franke_7(): ...
def franke_8(): ...
