from .. import cn as cn
from ..helpers import book as book
from ._helpers import C2Scheme as C2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete

def stroud_c2_1_1(): ...
def stroud_c2_3_1(): ...
def stroud_c2_3_2(): ...
def stroud_c2_3_3(): ...
def stroud_c2_5_4(): ...
def stroud_c2_7_4(): ...
