from ..helpers import QuadratureScheme as QuadratureScheme, plot_disks_1d as plot_disks_1d
from _typeshed import Incomplete

class E1r2Scheme(QuadratureScheme):
    domain: str
    def __init__(self, name, weights, points, degree, source: Incomplete | None = ...) -> None: ...
    def integrate(self, f, dot=...): ...
    def plot(self, show_axes: bool = ...) -> None: ...
