from ..helpers import article as article
from ._helpers import C3Scheme as C3Scheme, register as register

def hammer_stroud_1_3(): ...
def hammer_stroud_2_3(): ...
def hammer_stroud_4_3(): ...
def hammer_stroud_5_3a(): ...
def hammer_stroud_5_3b(): ...
def hammer_stroud_6_3(): ...
