# Generated by Django 4.0.8 on 2022-12-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netos_inventory', '0002_delete_networkfabric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lanconsolidationreport',
            options={'verbose_name': 'LAN consolidation report', 'verbose_name_plural': 'LAN consolidation reports'},
        ),
    ]
