VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('01')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 202302012012
version_date = '2023/02/01 20:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
