# flake8: noqa

"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0"

# import ApiClient
from apollo.api_client import ApiClient

# import Configuration
from apollo.configuration import Configuration

# import exceptions
from apollo.exceptions import OpenApiException
from apollo.exceptions import ApiAttributeError
from apollo.exceptions import ApiTypeError
from apollo.exceptions import ApiValueError
from apollo.exceptions import ApiKeyError
from apollo.exceptions import ApiException
