from ..helpers import QuadratureScheme as QuadratureScheme, backend_to_function as backend_to_function, expand_symmetries as expand_symmetries
from _typeshed import Incomplete

schemes: Incomplete

def register(in_schemes) -> None: ...

class E3rScheme(QuadratureScheme):
    symmetry_data: Incomplete
    domain: str
    def __init__(self, name, symmetry_data, degree, source, tol: float = ...) -> None: ...
    def integrate(self, f, dot=...): ...
    def show(self, backend: str = ...) -> None: ...

def get_good_scheme(degree): ...
