# file generated by 'build_algorithms.py'
from .loaders import load_params as _load


@_load
def crc_8():
	pass


@_load
def crc_8_cdma2000():
	pass


@_load
def crc_8_darc():
	pass


@_load
def crc_8_dvb_s2():
	pass


@_load
def crc_8_ebu():
	pass


@_load
def crc_8_i_code():
	pass


@_load
def crc_8_itu():
	pass


@_load
def crc_8_maxim():
	pass


@_load
def crc_8_rohc():
	pass


@_load
def crc_8_wcdma():
	pass


@_load
def crc_16_ccitt_false():
	pass


@_load
def crc_16_arc():
	pass


@_load
def crc_16_aug_ccitt():
	pass


@_load
def crc_16_buypass():
	pass


@_load
def crc_16_cdma2000():
	pass


@_load
def crc_16_dds_110():
	pass


@_load
def crc_16_dect_r():
	pass


@_load
def crc_16_dect_x():
	pass


@_load
def crc_16_dnp():
	pass


@_load
def crc_16_en_13757():
	pass


@_load
def crc_16_genibus():
	pass


@_load
def crc_16_maxim():
	pass


@_load
def crc_16_mcrf4xx():
	pass


@_load
def crc_16_riello():
	pass


@_load
def crc_16_t10_dif():
	pass


@_load
def crc_16_teledisk():
	pass


@_load
def crc_16_tms37157():
	pass


@_load
def crc_16_usb():
	pass


@_load
def crc_a():
	pass


@_load
def crc_16_kermit():
	pass


@_load
def crc_16_modbus():
	pass


@_load
def crc_16_x_25():
	pass


@_load
def crc_16_xmodem():
	pass


@_load
def crc_32():
	pass


@_load
def crc_32_bzip2():
	pass


@_load
def crc_32c():
	pass


@_load
def crc_32d():
	pass


@_load
def crc_32_mpeg_2():
	pass


@_load
def crc_32_posix():
	pass


@_load
def crc_32q():
	pass


@_load
def crc_32_jamcrc():
	pass


@_load
def crc_32_xfer():
	pass
