# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import chain_app_client_sdk
from chain_app_client_sdk.paths.main_pool_get_info import get  # noqa: E501
from chain_app_client_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestMainPoolGetInfo(ApiTestMixin, unittest.TestCase):
    """
    MainPoolGetInfo unit test stubs
        get pool size info  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
