from .._helpers import T3Scheme as T3Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def shunn_ham_1(): ...
def shunn_ham_2(): ...
def shunn_ham_3(): ...
def shunn_ham_4(): ...
def shunn_ham_5(): ...
def shunn_ham_6(): ...
