# generated by datamodel-codegen:
#   filename:  system_log_parameters_v1.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Extra, Field, constr
from typing_extensions import Literal


class ModelItem(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    message: constr(max_length=2048) = Field(
        ..., description="Message to add to system log."
    )
    level: Literal["debug", "info", "warn", "error"] = Field(
        ..., description="Log level: debug, info, warn, error."
    )


class Model(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: Union[List[ModelItem], ModelItem]
