# NMEA Plugin
DEFAULT_TCP_PORT = 10110
DEFAULT_BUFFER_SIZE = 4096
DEFAULT_SOCKET_TIMEOUT = 60

# Victron Plugin
MODBUS_TCP_PORT = 502

# Entry disk write interval in seconds
DEFAULT_DISK_WRITE_INTERVAL = 5

DEFAULT_FILENAME_PREFIX = "Trip_"
DEFAULT_SUMMARY_FILENAME_PREFIX = "Trip_Summary_"
DEFAULT_CSV_OUTPUT_FLAG = False
DEFAULT_EXCEL_OUTPUT_FLAG = False
DEFAULT_GPX_OUTPUT_FLAG = False
DEFAULT_SUMMARY_OUTPUT_FLAG = False
DEFAULT_VERBOSE_FLAG = False
DEFAULT_LIMITED_FLAG = False
