from ..helpers import QuadratureScheme as QuadratureScheme, plot_disks_1d as plot_disks_1d

class E1rScheme(QuadratureScheme):
    domain: str
    def __init__(self, name, weights, points, degree) -> None: ...
    def integrate(self, f, dot=...): ...
    def plot(self, show_axes: bool = ...) -> None: ...
