# generated by datamodel-codegen:
#   filename:  folder_creation_v1.json

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Extra, Field, constr
from typing_extensions import Literal


class Model(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    parent_uri: AnyUrl = Field(
        ..., description="The uri of folder to create the new folder in."
    )
    name: constr(min_length=1) = Field(..., description="The name for the folder.")
    on_dup_name: Optional[Literal["error", "auto_rename"]] = Field(
        "error", description="How to handle a duplicate name."
    )
