from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def wandzura_xiao_1(): ...
def wandzura_xiao_2(): ...
def wandzura_xiao_3(): ...
def wandzura_xiao_4(): ...
def wandzura_xiao_5(): ...
def wandzura_xiao_6(): ...
