from .._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def dunavant_01(): ...
def dunavant_02(): ...
def dunavant_03(): ...
def dunavant_04(): ...
def dunavant_05(): ...
def dunavant_06(): ...
def dunavant_07(): ...
def dunavant_08(): ...
def dunavant_09(): ...
def dunavant_10(): ...
def dunavant_11(): ...
def dunavant_12(): ...
def dunavant_13(): ...
def dunavant_14(): ...
def dunavant_15(): ...
def dunavant_16(): ...
def dunavant_17(): ...
def dunavant_18(): ...
def dunavant_19(): ...
def dunavant_20(): ...
