from .._exception import QuadpyError as QuadpyError
from ..helpers import QuadratureScheme as QuadratureScheme
from _typeshed import Incomplete
from typing import Callable

class TnScheme(QuadratureScheme):
    domain: Incomplete
    dim: Incomplete
    def __init__(self, name: str, dim: int, weights, points, degree: int, source, tol: float = ..., comments: Union[list[str], None] = ...) -> None: ...
    def points_inside(self): ...
    def points_inside_or_boundary(self): ...
    def integrate(self, f: Callable, simplex, dot=...): ...

def transform(points, simplex): ...
def get_vol(simplex): ...
