from ..helpers import article as article, rd as rd, untangle as untangle
from ._helpers import TnScheme as TnScheme
from _typeshed import Incomplete

source: Incomplete

def lauffer_1(n: int): ...
def lauffer_2(n: int): ...
def lauffer_3(n: int): ...
def lauffer_4(n: int): ...
def lauffer_5(n: int): ...
