from ..helpers import article as article, rd as rd, untangle as untangle
from ._helpers import TnScheme as TnScheme
from _typeshed import Incomplete

source: Incomplete

def stroud_1966_1(n): ...
def stroud_1966_2(n): ...
def stroud_1966_3(n): ...
def stroud_1966_4(n): ...
def stroud_1966_5(n): ...
def stroud_1966_6(n): ...
def stroud_1966_7(n): ...
