from ..helpers import techreport as techreport, untangle as untangle
from ._helpers import TnScheme as TnScheme
from _typeshed import Incomplete

source: Incomplete

def walkington_1(d): ...
def walkington_2(d): ...
def walkington_3(d): ...
def walkington_5(d): ...
def walkington_7(d): ...
