
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-02T16:22:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce73430f5f022a91badfedfa07f4999d8de866fd",
 "version": "2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
