from .._helpers import T3Scheme as T3Scheme, register as register
from _typeshed import Incomplete

this_dir: Incomplete

def witherden_vincent_01(): ...
def witherden_vincent_02(): ...
def witherden_vincent_03(): ...
def witherden_vincent_05(): ...
def witherden_vincent_06(): ...
def witherden_vincent_07(): ...
def witherden_vincent_08(): ...
def witherden_vincent_09(): ...
def witherden_vincent_10(): ...
