from ..helpers import article as article
from ._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete

def hammer_marlowe_stroud_1(): ...
def hammer_marlowe_stroud_2(): ...
def hammer_marlowe_stroud_3(): ...
def hammer_marlowe_stroud_4(): ...
def hammer_marlowe_stroud_5(): ...
