from ..helpers import article as article
from ._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete

def lyness_jespersen_01(): ...
def lyness_jespersen_02(): ...
def lyness_jespersen_03(): ...
def lyness_jespersen_05(): ...
def lyness_jespersen_06(): ...
def lyness_jespersen_07(): ...
def lyness_jespersen_08(): ...
def lyness_jespersen_09(): ...
def lyness_jespersen_11(): ...
def lyness_jespersen_12(): ...
def lyness_jespersen_13(): ...
def lyness_jespersen_14(): ...
def lyness_jespersen_15(): ...
def lyness_jespersen_16(): ...
def lyness_jespersen_17(): ...
def lyness_jespersen_18(): ...
def lyness_jespersen_19(): ...
def lyness_jespersen_20(): ...
def lyness_jespersen_21(): ...
triex_19 = lyness_jespersen_18
triex_28 = lyness_jespersen_21
