from .._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def williams_shunn_jameson_1(): ...
def williams_shunn_jameson_2(): ...
def williams_shunn_jameson_3(): ...
def williams_shunn_jameson_4(): ...
def williams_shunn_jameson_5(): ...
def williams_shunn_jameson_6(): ...
def williams_shunn_jameson_7(): ...
def williams_shunn_jameson_8(): ...
