from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def papanicolopulos_sym_0(): ...
def papanicolopulos_sym_1(): ...
def papanicolopulos_sym_2(): ...
def papanicolopulos_sym_3(): ...
def papanicolopulos_sym_4(): ...
def papanicolopulos_sym_5(): ...
def papanicolopulos_sym_6(): ...
def papanicolopulos_sym_7(): ...
def papanicolopulos_sym_8(): ...
def papanicolopulos_rot_08(): ...
def papanicolopulos_rot_09(): ...
def papanicolopulos_rot_10(): ...
def papanicolopulos_rot_11(): ...
def papanicolopulos_rot_12(): ...
def papanicolopulos_rot_13(): ...
def papanicolopulos_rot_14(): ...
def papanicolopulos_rot_15(): ...
def papanicolopulos_rot_16(): ...
def papanicolopulos_rot_17(): ...
