from .._helpers import register as register
from _typeshed import Incomplete

this_dir: Incomplete

def cools_haegemans_5_1(): ...
def cools_haegemans_9_1(): ...
def cools_haegemans_9_2(): ...
def cools_haegemans_13_1(): ...
