from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def xiao_gimbutas_01(): ...
def xiao_gimbutas_02(): ...
def xiao_gimbutas_03(): ...
def xiao_gimbutas_04(): ...
def xiao_gimbutas_05(): ...
def xiao_gimbutas_06(): ...
def xiao_gimbutas_07(): ...
def xiao_gimbutas_08(): ...
def xiao_gimbutas_09(): ...
def xiao_gimbutas_10(): ...
def xiao_gimbutas_11(): ...
def xiao_gimbutas_12(): ...
def xiao_gimbutas_13(): ...
def xiao_gimbutas_14(): ...
def xiao_gimbutas_15(): ...
