from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def fliege_maier_04(): ...
def fliege_maier_09(): ...
def fliege_maier_16(): ...
def fliege_maier_25(): ...
