from ..helpers import article as article, pm_roll as pm_roll, untangle as untangle
from ._helpers import U3Scheme as U3Scheme, register as register
from _typeshed import Incomplete

source: Incomplete

def mclaren_01(): ...
def mclaren_02(): ...
def mclaren_03(): ...
def mclaren_04(): ...
def mclaren_05(): ...
def mclaren_06(): ...
def mclaren_07(): ...
def mclaren_08(): ...
def mclaren_09(): ...
def mclaren_10(): ...
