from .._helpers import T3Scheme as T3Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def yu_2(): ...
def yu_3(): ...
def yu_4(): ...
def yu_5(): ...
def yu_6(): ...
