from ..helpers import article as article
from ._helpers import S3Scheme as S3Scheme, register as register
from _typeshed import Incomplete

frac: Incomplete
sqrt: Incomplete
pi: Incomplete

def hammer_stroud_11_3(): ...
def hammer_stroud_12_3(): ...
def hammer_stroud_14_3(variant_a: bool = ...): ...
def hammer_stroud_15_3a(): ...
def hammer_stroud_15_3b(): ...
