
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-02T04:27:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "93d8850eb270d5580c8303f61977f0ac5d0f4f83",
 "version": "1.18.1.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
