# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import learning_pb2 as learning__pb2


class LearningServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setLabel = channel.unary_unary(
                '/calixa.domain.learning.LearningService/setLabel',
                request_serializer=learning__pb2.SetLabelRequest.SerializeToString,
                response_deserializer=learning__pb2.Label.FromString,
                )
        self.getLabels = channel.unary_unary(
                '/calixa.domain.learning.LearningService/getLabels',
                request_serializer=learning__pb2.GetLabelRequest.SerializeToString,
                response_deserializer=learning__pb2.LabelList.FromString,
                )


class LearningServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLabels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.setLabel,
                    request_deserializer=learning__pb2.SetLabelRequest.FromString,
                    response_serializer=learning__pb2.Label.SerializeToString,
            ),
            'getLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.getLabels,
                    request_deserializer=learning__pb2.GetLabelRequest.FromString,
                    response_serializer=learning__pb2.LabelList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calixa.domain.learning.LearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearningService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.learning.LearningService/setLabel',
            learning__pb2.SetLabelRequest.SerializeToString,
            learning__pb2.Label.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.learning.LearningService/getLabels',
            learning__pb2.GetLabelRequest.SerializeToString,
            learning__pb2.LabelList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
