
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-01T12:00:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "de4ece272dfc67a9868432d89178144e7760dcd5",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
