# coding: utf-8

"""
    Copilot SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    Generated by: https://openapi-generator.tech
"""

import unittest

import copilot_platform_sdk
from copilot_platform_sdk.model.dispatcher_error import DispatcherError
from copilot_platform_sdk import configuration


class TestDispatcherError(unittest.TestCase):
    """DispatcherError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
