# generated by datamodel-codegen:
#   filename:  connector_delete_response_v1.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class Model(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    success: bool = Field(..., description="Connector unlinking success response.")
