from .._helpers import T2Scheme as T2Scheme, register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def strang_fix_cowper_01(): ...
def strang_fix_cowper_03(): ...
def strang_fix_cowper_04(): ...
def strang_fix_cowper_05(): ...
def strang_fix_cowper_06(): ...
def strang_fix_cowper_07(): ...
def strang_fix_cowper_08(): ...
def strang_fix_cowper_09(): ...
def strang_fix_cowper_10(): ...
