from .._exception import QuadpyError as QuadpyError
from ..helpers import QuadratureScheme as QuadratureScheme
from _typeshed import Incomplete

class SnScheme(QuadratureScheme):
    domain: Incomplete
    dim: Incomplete
    def __init__(self, name, dim, weights, points, degree, source, tol: float = ...) -> None: ...
    def points_inside(self): ...
    def points_inside_or_boundary(self): ...
    def integrate(self, f, center, radius, dot=...): ...
