from ..helpers import fsd as fsd, untangle as untangle, z as z
from ._helpers import SnScheme as SnScheme

def stenger_7a(n): ...
def stenger_7b(n): ...
def stenger_9a(n): ...
def stenger_9b(n): ...
def stenger_11a(n): ...
def stenger_11b(n): ...
