from ..helpers import article as article, combine as combine, fsd as fsd, pm as pm, untangle as untangle, z as z
from ._helpers import SnScheme as SnScheme
from _typeshed import Incomplete

source: Incomplete

def stroud_1966_a(n, symbolic: bool = ...): ...
def stroud_1966_b(n, symbolic: bool = ...): ...
def stroud_1966_c(n, symbolic: bool = ...): ...
def stroud_1966_d(n, symbolic: bool = ...): ...
