# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ActionAssignmentElement(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "assignedUser",
        }
        
        class properties:
            assignedUser = schemas.StrSchema
            __annotations__ = {
                "assignedUser": assignedUser,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    assignedUser: MetaOapg.properties.assignedUser
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assignedUser"]) -> MetaOapg.properties.assignedUser: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["assignedUser"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assignedUser"]) -> MetaOapg.properties.assignedUser: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["assignedUser"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        assignedUser: typing.Union[MetaOapg.properties.assignedUser, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ActionAssignmentElement':
        return super().__new__(
            cls,
            *args,
            assignedUser=assignedUser,
            _configuration=_configuration,
        )
