# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class GetModelInsightsResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "insights",
        }
        
        class properties:
            
            
            class insights(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Insight']:
                        return Insight
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Insight'], typing.List['Insight']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'insights':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Insight':
                    return super().__getitem__(i)
            __annotations__ = {
                "insights": insights,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    insights: MetaOapg.properties.insights
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["insights"]) -> MetaOapg.properties.insights: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["insights"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["insights"]) -> MetaOapg.properties.insights: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["insights"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        insights: typing.Union[MetaOapg.properties.insights, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'GetModelInsightsResponse':
        return super().__new__(
            cls,
            *args,
            insights=insights,
            _configuration=_configuration,
        )

from openapi_client.model.insight import Insight
