# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class LoadModelResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "model",
        }
        
        class properties:
        
            @staticmethod
            def model() -> typing.Type['ModelPopulatedJob']:
                return ModelPopulatedJob
            __annotations__ = {
                "model": model,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    model: 'ModelPopulatedJob'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model"]) -> 'ModelPopulatedJob': ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["model"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model"]) -> 'ModelPopulatedJob': ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["model"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        model: 'ModelPopulatedJob',
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'LoadModelResponse':
        return super().__new__(
            cls,
            *args,
            model=model,
            _configuration=_configuration,
        )

from openapi_client.model.model_populated_job import ModelPopulatedJob
