# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ModelTestData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "epoch",
            "modelExtId",
        }
        
        class properties:
            modelExtId = schemas.StrSchema
            epoch = schemas.Float64Schema
            __annotations__ = {
                "modelExtId": modelExtId,
                "epoch": epoch,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    epoch: MetaOapg.properties.epoch
    modelExtId: MetaOapg.properties.modelExtId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["epoch"]) -> MetaOapg.properties.epoch: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modelExtId"]) -> MetaOapg.properties.modelExtId: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["epoch"], typing_extensions.Literal["modelExtId"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["epoch"]) -> MetaOapg.properties.epoch: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modelExtId"]) -> MetaOapg.properties.modelExtId: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["epoch"], typing_extensions.Literal["modelExtId"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        epoch: typing.Union[MetaOapg.properties.epoch, decimal.Decimal, int, float, ],
        modelExtId: typing.Union[MetaOapg.properties.modelExtId, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ModelTestData':
        return super().__new__(
            cls,
            *args,
            epoch=epoch,
            modelExtId=modelExtId,
            _configuration=_configuration,
        )
