# coding: utf-8

"""
    Chain App BIND client SDK

    Description for BIND.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bind.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import chain_app_client_sdk
from chain_app_client_sdk.model.request_user import RequestUser
from chain_app_client_sdk import configuration


class TestRequestUser(unittest.TestCase):
    """RequestUser unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
