
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-04T20:01:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "73fd134068696e57847d2be8967766a2034b36a6",
 "version": "v1.0.0rc9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
