from ..helpers import article as article, fsd as fsd, pm as pm, untangle as untangle
from ._helpers import EnrScheme as EnrScheme
from _typeshed import Incomplete

source: Incomplete

def stroud_secrest_1(n): ...
def stroud_secrest_2(n): ...
def stroud_secrest_3(n): ...
def stroud_secrest_4(n): ...
