from .._helpers import C3Scheme as C3Scheme, register as register
from _typeshed import Incomplete

this_dir: Incomplete

def witherden_vincent_07(): ...
def witherden_vincent_09(): ...
def witherden_vincent_11(): ...
