from .._helpers import register as register
from _typeshed import Incomplete

this_dir: Incomplete

def rabinowitz_richter_1(): ...
def rabinowitz_richter_2(): ...
def rabinowitz_richter_3(): ...
def rabinowitz_richter_4(): ...
def rabinowitz_richter_5(): ...
def rabinowitz_richter_6(): ...
