# coding: utf-8

"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.237
    Generated by: https://openapi-generator.tech
"""

from tensorleap-openapi-client.paths.auth_activate.post import Activate
from tensorleap-openapi-client.paths.dashboards_add_dashboard.post import AddDashboard
from tensorleap-openapi-client.paths.datasets_add_dataset.post import AddDataset
from tensorleap-openapi-client.paths.jobs_add_export_model_job.post import AddExportModelJob
from tensorleap-openapi-client.paths.issues_add_issue.post import AddIssue
from tensorleap-openapi-client.paths.projects_add_project.post import AddProject
from tensorleap-openapi-client.paths.secret_manager_add_secret_manager.post import AddSecretManager
from tensorleap-openapi-client.paths.versions_add_version.post import AddVersion
from tensorleap-openapi-client.paths.jobs_continue_train.post import ContinueTrain
from tensorleap-openapi-client.paths.model_tests_create_model_test.post import CreateModelTest
from tensorleap-openapi-client.paths.organizations_create_organization.post import CreateOrganization
from tensorleap-openapi-client.paths.dashboards_delete_dashboard.post import DeleteDashboard
from tensorleap-openapi-client.paths.issues_delete_issue.post import DeleteIssue
from tensorleap-openapi-client.paths.models_delete_model.post import DeleteModel
from tensorleap-openapi-client.paths.model_tests_delete_model_test.post import DeleteModelTest
from tensorleap-openapi-client.paths.organizations_delete_organization.post import DeleteOrganization
from tensorleap-openapi-client.paths.projects_delete_project.post import DeleteProject
from tensorleap-openapi-client.paths.users_delete_user_by_id.post import DeleteUserById
from tensorleap-openapi-client.paths.versions_delete_version.post import DeleteVersion
from tensorleap-openapi-client.paths.visualizations_delete_visualizations.post import DeleteVisualizations
from tensorleap-openapi-client.paths.jobs_evaluate.post import Evaluate
from tensorleap-openapi-client.paths.auth_extend_trial.post import ExtendTrial
from tensorleap-openapi-client.paths.model_tests_get_all_project_model_tests.post import GetAllProjectModelTests
from tensorleap-openapi-client.paths.users_get_all_slim_user_data.post import GetAllSlimUserData
from tensorleap-openapi-client.paths.modelmetrics_get_balanced_accuracy.post import GetBalancedAccuracy
from tensorleap-openapi-client.paths.modelmetrics_get_confusion_metric_names.post import GetConfusionMetricNames
from tensorleap-openapi-client.paths.projects_get_current_project_version.post import GetCurrentProjectVersion
from tensorleap-openapi-client.paths.dashboards_get_dashboard.post import GetDashboard
from tensorleap-openapi-client.paths.dashboards_get_dashlet_fields.post import GetDashletFields
from tensorleap-openapi-client.paths.datasets_get_dataset_version.post import GetDatasetVersion
from tensorleap-openapi-client.paths.datasets_get_dataset_versions.post import GetDatasetVersions
from tensorleap-openapi-client.paths.datasets_get_datasets.post import GetDatasets
from tensorleap-openapi-client.paths.demos_get_demos.post import GetDemos
from tensorleap-openapi-client.paths.exportedmodels_get_exported_model_jobs.post import GetExportedModelJobs
from tensorleap-openapi-client.paths.modelmetrics_get_f1_score.post import GetF1Score
from tensorleap-openapi-client.paths.modelmetrics_get_heatmap_chart.post import GetHeatmapChart
from tensorleap-openapi-client.paths.jobs_get_jobs.post import GetJobs
from tensorleap-openapi-client.paths.dashboards_get_kibana_dashboards.post import GetKibanaDashboards
from tensorleap-openapi-client.paths.dashboards_get_kibana_dashlet_fields.post import GetKibanaDashletFields
from tensorleap-openapi-client.paths.datasets_get_latest_dataset_version.post import GetLatestDatasetVersion
from tensorleap-openapi-client.paths.jobs_get_machine_types.post import GetMachineTypes
from tensorleap-openapi-client.paths.metadata_get_max_active_users.post import GetMaxActiveUsers
from tensorleap-openapi-client.paths.modelmetrics_get_model_epoch_loss.post import GetModelEpochLoss
from tensorleap-openapi-client.paths.insights_get_model_insights.post import GetModelInsights
from tensorleap-openapi-client.paths.model_tests_get_model_test_result.post import GetModelTestResult
from tensorleap-openapi-client.paths.visualizations_get_model_visualizations.post import GetModelVisualizations
from tensorleap-openapi-client.paths.models_get_models_by_hash.post import GetModelsByHash
from tensorleap-openapi-client.paths.models_get_models_by_version_id.post import GetModelsByVersionId
from tensorleap-openapi-client.paths.notifications_get_notifications.post import GetNotifications
from tensorleap-openapi-client.paths.jobs_get_organization_jobs.post import GetOrganizationJobs
from tensorleap-openapi-client.paths.users_get_organization_slim_user_data.post import GetOrganizationSlimUserData
from tensorleap-openapi-client.paths.organizations_get_organizations.post import GetOrganizations
from tensorleap-openapi-client.paths.modelmetrics_get_pr_curve.post import GetPrCurve
from tensorleap-openapi-client.paths.dashboards_get_project_dashboards.post import GetProjectDashboards
from tensorleap-openapi-client.paths.issues_get_project_issues.post import GetProjectIssues
from tensorleap-openapi-client.paths.versions_get_project_slim_versions.post import GetProjectSlimVersions
from tensorleap-openapi-client.paths.projects_get_projects.post import GetProjects
from tensorleap-openapi-client.paths.models_get_recent_organization_models.post import GetRecentOrganizationModels
from tensorleap-openapi-client.paths.modelmetrics_get_roc.post import GetRoc
from tensorleap-openapi-client.paths.secret_manager_get_secret_manager_list.post import GetSecretManagerList
from tensorleap-openapi-client.paths.issues_get_single_issue.post import GetSingleIssue
from tensorleap-openapi-client.paths.model_tests_get_single_model_test.post import GetSingleModelTest
from tensorleap-openapi-client.paths.metadata_get_statistics.post import GetStatistics
from tensorleap-openapi-client.paths.exportedmodels_get_stored_exported_model_resource_url.post import GetStoredExportedModelResourceUrl
from tensorleap-openapi-client.paths.visualizations_get_stored_resource_url.post import GetStoredResourceUrl
from tensorleap-openapi-client.paths.modelmetrics_get_table_chart.post import GetTableChart
from tensorleap-openapi-client.paths.jobs_get_training_jobs.post import GetTrainingJobs
from tensorleap-openapi-client.paths.versions_get_upload_signed_url.post import GetUploadSignedUrl
from tensorleap-openapi-client.paths.visualizations_get_visualization.post import GetVisualization
from tensorleap-openapi-client.paths.modelmetrics_get_xy_chart.post import GetXyChart
from tensorleap-openapi-client.paths.monitor_health_check.get import HealthCheck
from tensorleap-openapi-client.paths.demos_import_demo_project.post import ImportDemoProject
from tensorleap-openapi-client.paths.versions_import_model.post import ImportModel
from tensorleap-openapi-client.paths.jobs_is_training_job_running.post import IsTrainingJobRunning
from tensorleap-openapi-client.paths.auth_keygen.post import KeyGen
from tensorleap-openapi-client.paths.auth_keylogin.post import KeyLogin
from tensorleap-openapi-client.paths.projects_load_model.post import LoadModel
from tensorleap-openapi-client.paths.versions_load_version.post import LoadVersion
from tensorleap-openapi-client.paths.auth_login.post import Login
from tensorleap-openapi-client.paths.auth_logout.post import Logout
from tensorleap-openapi-client.paths.datasets_modify_dataset_version_note.post import ModifyDatasetVersionNote
from tensorleap-openapi-client.paths.datasets_parse_dataset.post import ParseDataset
from tensorleap-openapi-client.paths.jobs_population_exploration.post import PopulationExploration
from tensorleap-openapi-client.paths.auth_request_trial.post import RequestTrial
from tensorleap-openapi-client.paths.auth_resend_activation_mail.post import ResendActivationMail
from tensorleap-openapi-client.paths.auth_reset_password.post import ResetPassword
from tensorleap-openapi-client.paths.jobs_sample_analysis.post import SampleAnalysis
from tensorleap-openapi-client.paths.jobs_sample_selection.post import SampleSelection
from tensorleap-openapi-client.paths.visualizations_save_analyzer_layout.post import SaveAnalyzerLayout
from tensorleap-openapi-client.paths.datasets_save_dataset_version.post import SaveDatasetVersion
from tensorleap-openapi-client.paths.auth_send_reset_password_mail.post import SendResetPasswordMail
from tensorleap-openapi-client.paths.demos_send_user_message.post import SendUserMessage
from tensorleap-openapi-client.paths.organizations_set_default_organization.post import SetDefaultOrganization
from tensorleap-openapi-client.paths.jobs_set_machine_type.post import SetOrganizationMachineType
from tensorleap-openapi-client.paths.auth_set_user_metadata.post import SetUserMetadata
from tensorleap-openapi-client.paths.notifications_set_user_notifications_as_read.post import SetUserNotificationsAsRead
from tensorleap-openapi-client.paths.auth_signup.post import Signup
from tensorleap-openapi-client.paths.auth_start_trial.post import StartTrial
from tensorleap-openapi-client.paths.jobs_stop_job.post import StopJob
from tensorleap-openapi-client.paths.jobs_terminate_job.post import TerminateJob
from tensorleap-openapi-client.paths.jobs_train_from_initial_weights.post import TrainFromInitialWeights
from tensorleap-openapi-client.paths.jobs_train_from_scratch.post import TrainFromScratch
from tensorleap-openapi-client.paths.datasets_trash_dataset.post import TrashDataset
from tensorleap-openapi-client.paths.projects_trash_project.post import TrashProject
from tensorleap-openapi-client.paths.secret_manager_trash_secret_manager.post import TrashSecretManager
from tensorleap-openapi-client.paths.dashboards_update_dashboard.post import UpdateDashboard
from tensorleap-openapi-client.paths.issues_update_issue.post import UpdateIssue
from tensorleap-openapi-client.paths.model_tests_update_model_test.post import UpdateModelTest
from tensorleap-openapi-client.paths.organizations_update_organization_public_name.post import UpdateOrganizationPublicName
from tensorleap-openapi-client.paths.secret_manager_update_secret_manager.post import UpdateSecretManager
from tensorleap-openapi-client.paths.users_update_user_name.post import UpdateUserName
from tensorleap-openapi-client.paths.users_update_user_organization.post import UpdateUserOrganization
from tensorleap-openapi-client.paths.users_update_user_role.post import UpdateUserRole
from tensorleap-openapi-client.paths.users_update_user_status.post import UpdateUserStatus
from tensorleap-openapi-client.paths.versions_update_version.post import UpdateVersion
from tensorleap-openapi-client.paths.jobs_warmup.post import Warmup
from tensorleap-openapi-client.paths.auth_who_am_i.post import WhoAmI


class DefaultApi(
    Activate,
    AddDashboard,
    AddDataset,
    AddExportModelJob,
    AddIssue,
    AddProject,
    AddSecretManager,
    AddVersion,
    ContinueTrain,
    CreateModelTest,
    CreateOrganization,
    DeleteDashboard,
    DeleteIssue,
    DeleteModel,
    DeleteModelTest,
    DeleteOrganization,
    DeleteProject,
    DeleteUserById,
    DeleteVersion,
    DeleteVisualizations,
    Evaluate,
    ExtendTrial,
    GetAllProjectModelTests,
    GetAllSlimUserData,
    GetBalancedAccuracy,
    GetConfusionMetricNames,
    GetCurrentProjectVersion,
    GetDashboard,
    GetDashletFields,
    GetDatasetVersion,
    GetDatasetVersions,
    GetDatasets,
    GetDemos,
    GetExportedModelJobs,
    GetF1Score,
    GetHeatmapChart,
    GetJobs,
    GetKibanaDashboards,
    GetKibanaDashletFields,
    GetLatestDatasetVersion,
    GetMachineTypes,
    GetMaxActiveUsers,
    GetModelEpochLoss,
    GetModelInsights,
    GetModelTestResult,
    GetModelVisualizations,
    GetModelsByHash,
    GetModelsByVersionId,
    GetNotifications,
    GetOrganizationJobs,
    GetOrganizationSlimUserData,
    GetOrganizations,
    GetPrCurve,
    GetProjectDashboards,
    GetProjectIssues,
    GetProjectSlimVersions,
    GetProjects,
    GetRecentOrganizationModels,
    GetRoc,
    GetSecretManagerList,
    GetSingleIssue,
    GetSingleModelTest,
    GetStatistics,
    GetStoredExportedModelResourceUrl,
    GetStoredResourceUrl,
    GetTableChart,
    GetTrainingJobs,
    GetUploadSignedUrl,
    GetVisualization,
    GetXyChart,
    HealthCheck,
    ImportDemoProject,
    ImportModel,
    IsTrainingJobRunning,
    KeyGen,
    KeyLogin,
    LoadModel,
    LoadVersion,
    Login,
    Logout,
    ModifyDatasetVersionNote,
    ParseDataset,
    PopulationExploration,
    RequestTrial,
    ResendActivationMail,
    ResetPassword,
    SampleAnalysis,
    SampleSelection,
    SaveAnalyzerLayout,
    SaveDatasetVersion,
    SendResetPasswordMail,
    SendUserMessage,
    SetDefaultOrganization,
    SetOrganizationMachineType,
    SetUserMetadata,
    SetUserNotificationsAsRead,
    Signup,
    StartTrial,
    StopJob,
    TerminateJob,
    TrainFromInitialWeights,
    TrainFromScratch,
    TrashDataset,
    TrashProject,
    TrashSecretManager,
    UpdateDashboard,
    UpdateIssue,
    UpdateModelTest,
    UpdateOrganizationPublicName,
    UpdateSecretManager,
    UpdateUserName,
    UpdateUserOrganization,
    UpdateUserRole,
    UpdateUserStatus,
    UpdateVersion,
    Warmup,
    WhoAmI,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
