from .cs import ColorCoordinates as ColorCoordinates, ColorSpace as ColorSpace, convert as convert, string_to_cs as string_to_cs

def save_rgb_gamut(filename: str, colorspace: Union[ColorSpace, str], variant: str = ..., n: int = ...) -> None: ...
def plot_rgb_gamut(colorspace: Union[ColorSpace, str], n: int = ..., show_grid: bool = ...): ...
def plot_rgb_slice(colorspace: Union[ColorSpace, str], lightness: float, camera_elevation: float, n: int = ..., variant: str = ..., off_screen: bool = ...): ...
