from ._helpers import SpectralData as SpectralData
from _typeshed import Incomplete

this_dir: Incomplete

def cie_1931_2(stepsize: int = ...): ...
def cie_1964_10(stepsize: int = ...): ...
def wws_cie_1931_2(lmbda): ...
def wws_cie_1964_10(lmbda): ...
