"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.case_update_pacer_options_response import CaseUpdatePacerOptionsResponse
from apollo.model.exception import Exception
globals()['CaseUpdatePacerOptionsResponse'] = CaseUpdatePacerOptionsResponse
globals()['Exception'] = Exception
from apollo.model.last_tracked_details import LastTrackedDetails


class TestLastTrackedDetails(unittest.TestCase):
    """LastTrackedDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLastTrackedDetails(self):
        """Test LastTrackedDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LastTrackedDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
