"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import unittest

import apollo
from apiv2.case_history_api import CaseHistoryApi  # noqa: E501


class TestCaseHistoryApi(unittest.TestCase):
    """CaseHistoryApi unit test stubs"""

    def setUp(self):
        self.api = CaseHistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_case_documents_history_for_case(self):
        """Test case for get_case_documents_history_for_case

        (NOT AVAILABLE) History of CaseDocuments.  # noqa: E501
        """
        pass

    def test_get_case_documents_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_case_documents_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of CaseDocuments By Date.  # noqa: E501
        """
        pass

    def test_get_docket_entries_history_for_case(self):
        """Test case for get_docket_entries_history_for_case

        (NOT AVAILABLE) History of DocketEntries.  # noqa: E501
        """
        pass

    def test_get_docket_entries_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_docket_entries_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of DocketEntries By Date.  # noqa: E501
        """
        pass

    def test_get_hearing_history_for_case(self):
        """Test case for get_hearing_history_for_case

        (NOT AVAILABLE) History of Hearings.  # noqa: E501
        """
        pass

    def test_get_hearing_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_hearing_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of Hearings By Date.  # noqa: E501
        """
        pass

    def test_get_judges_history_for_case(self):
        """Test case for get_judges_history_for_case

        (NOT AVAILABLE) History of Judges.  # noqa: E501
        """
        pass

    def test_get_judges_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_judges_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of Judges By Date.  # noqa: E501
        """
        pass

    def test_get_party_attorney_associations_history_for_case(self):
        """Test case for get_party_attorney_associations_history_for_case

        (NOT AVAILABLE) History of PartyAttorneyAssociations.  # noqa: E501
        """
        pass

    def test_get_party_attorney_associations_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_party_attorney_associations_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of PartyAttorneyAssociations By Date.  # noqa: E501
        """
        pass

    def test_get_related_case_history_for_case(self):
        """Test case for get_related_case_history_for_case

        (NOT AVAILABLE) History of RelatedCases.  # noqa: E501
        """
        pass

    def test_get_related_case_history_for_case_bylast_fetch_date_with_updates(self):
        """Test case for get_related_case_history_for_case_bylast_fetch_date_with_updates

        (NOT AVAILABLE) History of RelatedCases By Date.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
