"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.party_role import PartyRole
globals()['PartyRole'] = PartyRole
from apollo.model.party_role_response import PartyRoleResponse


class TestPartyRoleResponse(unittest.TestCase):
    """PartyRoleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartyRoleResponse(self):
        """Test PartyRoleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartyRoleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
