"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.docket_entries_history_by_date import DocketEntriesHistoryByDate
globals()['DocketEntriesHistoryByDate'] = DocketEntriesHistoryByDate
from apollo.model.docket_entries_histories import DocketEntriesHistories


class TestDocketEntriesHistories(unittest.TestCase):
    """DocketEntriesHistories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocketEntriesHistories(self):
        """Test DocketEntriesHistories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocketEntriesHistories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
