"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.case_count_analytics_by_norm_attorney import CaseCountAnalyticsByNormAttorney


class TestCaseCountAnalyticsByNormAttorney(unittest.TestCase):
    """CaseCountAnalyticsByNormAttorney unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByNormAttorney(self):
        """Test CaseCountAnalyticsByNormAttorney"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByNormAttorney()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
