"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.source_charge_additional_data import SourceChargeAdditionalData
globals()['SourceChargeAdditionalData'] = SourceChargeAdditionalData
from apollo.model.source_charge import SourceCharge


class TestSourceCharge(unittest.TestCase):
    """SourceCharge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceCharge(self):
        """Test SourceCharge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceCharge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
