"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.bar_record_preview import BarRecordPreview
from apollo.model.case_timeline import CaseTimeline
globals()['BarRecordPreview'] = BarRecordPreview
globals()['CaseTimeline'] = CaseTimeline
from apollo.model.associated_norm_attorney import AssociatedNormAttorney


class TestAssociatedNormAttorney(unittest.TestCase):
    """AssociatedNormAttorney unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedNormAttorney(self):
        """Test AssociatedNormAttorney"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociatedNormAttorney()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
