"""
    UniCourt API v2 - Beta APIs

    <button><a href=\"/apiv2/download/UniCourt-APIv2-Spec.yaml\" >Download Legal Analytics API Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apollo
from apollo.model.attorney_attorney_analytics_api import AttorneyAttorneyAnalyticsAPI
from apollo.model.attorney_law_firm import AttorneyLawFirm
from apollo.model.attorney_type import AttorneyType
from apollo.model.contact import Contact
from apollo.model.party_attorney_associations import PartyAttorneyAssociations
globals()['AttorneyAttorneyAnalyticsAPI'] = AttorneyAttorneyAnalyticsAPI
globals()['AttorneyLawFirm'] = AttorneyLawFirm
globals()['AttorneyType'] = AttorneyType
globals()['Contact'] = Contact
globals()['PartyAttorneyAssociations'] = PartyAttorneyAssociations
from apollo.model.attorney import Attorney


class TestAttorney(unittest.TestCase):
    """Attorney unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttorney(self):
        """Test Attorney"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attorney()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
