from .._helpers import register as register
from _typeshed import Incomplete

source: Incomplete
this_dir: Incomplete

def wissmann_becker_4_1(): ...
def wissmann_becker_4_2(): ...
def wissmann_becker_6_1(): ...
def wissmann_becker_6_2(): ...
def wissmann_becker_8_1(): ...
def wissmann_becker_8_2(): ...
